version: "3.9"

services:
  api-preregistration:
    container_name: "front-landingpage"
    image: "image-landingpage"
    ports:
      - 80:80
    env_file:
      - front-landingpage.env
    stdin_open: true
